name: 'Release System'
description: 'Releases the system using Docker Compose'
inputs:
  working-directory:
    description: 'Working directory where docker-compose.yml is located'
    required: false
    default: '.'
runs:
  using: 'composite'
  steps:
    - name: Release System
      run: docker compose up -d
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      # NOTE: In real life applications, you'd be deploying your System to some Environment
      # For this demo application, I'm using Docker Compose