name: acceptance-stage-test-dotnet

on:
  push:
    branches: [ "main" ]
    paths:
        - 'system-test-dotnet/**'
        - '.github/workflows/acceptance-stage-test-dotnet.yml'
  pull_request:
    branches: [ "main" ]
    paths:
        - 'system-test-dotnet/**'
        - '.github/workflows/acceptance-stage-test-dotnet.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Release System and Run Tests
      uses: ./.github/actions/release-system-test-dotnet
      with:
        working-directory: system-test-dotnet

    - name: Run Acceptance Tests
      run: echo "Run Acceptance Tests"

    - name: Run External System Contract Tests
      run: echo "Run External System Contract Tests"

    - name: Run E2E Tests
      run: echo "Run E2E Tests"
  
  hello-world:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello World
      run: echo "hello world"