name: prod-stage-test-java

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Release System
      uses: ./.github/actions/release-system-test-java
      with:
        working-directory: system-test-java